name: Run Tests Manually with Sequential Jobs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment (qa/preprod/prod)'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - preprod
          - prod
      browser:
        description: 'Select Browser (chrome/firefox/edge)'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge
      test_type:
        description: 'Type of Testing (smoke/regression)'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install ChromeDriver (Matching Chrome Version)
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          echo "Detected Chrome Version: $CHROME_VERSION"
          
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
          if [[ -z "$CHROMEDRIVER_VERSION" ]]; then
            echo "Could not find the exact ChromeDriver version for Chrome $CHROME_VERSION, falling back to latest release."
            CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          fi
          
          echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Install Xvfb (Virtual Display)
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven tests
        run: |
          export DISPLAY=:99
          mvn test -P ${{ github.event.inputs.environment }} -P ${{ github.event.inputs.test_type }} -P ${{ github.event.inputs.browser }}
        working-directory: Selenium

  publish-report:
    name: Publish Extent Report
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: Selenium/target/extent-reports/**/*.html
